
services:
  emqx:
    image: emqx/emqx-enterprise:6.2.2
    container_name: emqx
    extra_hosts:
      - "node1.cluster.local:127.0.0.1"
    ports:
      - "1883:1883"   # MQTT TCP
      - "8883:8883"   # MQTT SSL/TLS
      - "8083:8083"   # MQTT WebSockets
      - "8084:8084"   # MQTT WSS
      - "18083:18083" # Dashboard UI
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    environment:
      EMQX_NODE_NAME: emqx@node1.cluster.local
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: emqx
      POSTGRES_PASSWORD: emqx
      POSTGRES_DB: emqx
      EMQX_CONNECTORS__PGSQL__POSTGRES_CONN__SERVER: "${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}"
      EMQX_CONNECTORS__PGSQL__POSTGRES_CONN__DATABASE: "${POSTGRES_DB:-emqx}"
      EMQX_CONNECTORS__PGSQL__POSTGRES_CONN__USERNAME: "${POSTGRES_USER:-emqx}"
      EMQX_CONNECTORS__PGSQL__POSTGRES_CONN__PASSWORD: "${POSTGRES_PASSWORD:-emqx}"
    networks:
      - emqx-postgres-bridge
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    volumes:
      - $PWD/dockerdata/emqx:/opt/emqx/data
      - $PWD/emqx/rules.conf:/opt/emqx/etc/base.hocon:ro

    depends_on:
      - postgres

  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: emqx
      POSTGRES_PASSWORD: emqx
      POSTGRES_DB: emqx
    ports:
      - "5432:5432"
    volumes:
      - $PWD/dockerdata/postgres:/var/lib/postgresql
      - $PWD/database/db.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - emqx-postgres-bridge

networks:
  emqx-postgres-bridge:
    driver: bridge