api {
  web_server: http://localhost:30988
  api_server: http://localhost:30908
  files_server: http://localhost:30981
  credentials {
    "access_key": "A3EMA4YY67H1R9W8ISHYDXE3JE4VI6"
    "secret_key": "kqdQb0G-WUx-NnKw0Je3WEfm5oMLj80ZTwTo-sbEmGDjmLzWWgkNti5BnwzNaErxWyQ"
  }
}
