DatapointsFT = (
    "y" => [0*256 float],
    "x" => [0*256 float],
    "z" => [0*256 float]
)
DatapointsRT = (
    "y" => [0*512 uint],
    "x" => [0*512 uint],
    "z" => [0*512 uint]
)
Segment = {
    "id" => uint,
    "ss_id"=> uint, ; super segment id (for sequential segments)
    "rt" => bool, ; are there rt datapoints
    "ft"=> bool, ; are there ft datapoints
    "data" =>{
        "gyro_rt"=> DatapointsRT,
        "axel_rt"=> DatapointsRT,
        "gyro_ft"=> DatapointsFT,
        "axel_ft"=> DatapointsFT,
    }
}