apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    url: postgres:5432
    database: ${POSTGRES_DB:-emqx}
    user: ${POSTGRES_USER:-emqx}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-emqx}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
