apiVersion: 1
datasources:
  - name: TimescaleDB
    uid: TimescaleDB
    type: postgres
    url: postgres:5432
    database: emqx
    user: emqx
    secureJsonData:
      password: emqx
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
